# The URL the site will be built for
base_url = "https://richardmuri.github.io/"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true
theme = "simple-dev-blog"
taxonomies = [{name = "tags"}]
[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here
dark_mode = false
nav = [
  { name = "About", path = "/about/" },
  { name = "Paper Reviews", path = "/paper_reviews/" }
]
blog_path = "paper_reviews"
latest_text = "Check out my latest post:"

icon = "icon.jpg"
profile_small = "icon.jpg"
profile_large = "profile.jpg"

github = "Github-Mark-64px.png"

accent = "#05a081"
accent_light = "#82d0c0"

author = "Richard Muri"

footer_about = """
A personal website based on the simple-dev-blog theme.
"""

footer_page = """
© 2022, all rights reserved
"""

not_found_message = """
This is not the page you're looking for... return back to [safety?](/)
"""